services:
  accounts:
    image: "athifizdoc/accounts:0.1"
    container_name: accounts-ms
    ports:
      - "8080:8080"
      - "8081:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - "athifiz"

  loans:
    image: "athifizdoc/loans:0.1"
    container_name: loans-ms
    ports:
      - "8090:8090"
      - "8091:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - "athifiz"

  cards:
    image: "athifizdoc/cards:0.1"
    container_name: cards-ms
    ports:
      - "9000:9000"
      - "9001:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - "athifiz"

networks:
  athifiz:
    driver: "bridge"
