server:
  port: 8090

spring:
  application:
    name: "loans"

  profiles:
    active: "prod"

  datasource:
    url: jdbc:mysql://localhost:4307/loansdb
    username: root
    password: root
    jpa:
      show-sql: true
  sql:
    init:
      mode: always   # telling spring boot to execute the script inside schema.sql

  config:
    import: "optional:configserver:http://localhost:8071/"

#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*" # telling enable and expose all management endpoints supported by actuator(one of them is refresh related endpoints)

  info:
    env:
      enabled: true

  endpoint:
    shutdown:
      access: unrestricted
    health:
      probes:
        enabled: true

  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "loans"
    description: "Loans application of the Bank"
    version: "0.4"