server:
  port: 8080

spring:
  application:
    name: "accounts"

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

  #Activates a profile by default
  profiles:
    active: prod

  datasource:
#    url: jdbc:h2:mem:testdb  #  Uses an in-memory H2 database named testdb
#    driverClassName: org.h2.Driver  #    Tells Spring which JDBC driver to use (H2 in this case).
#    username: sa
#    password: ''
    url: jdbc:mysql://localhost:4306/accountsdb
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always   # telling spring boot to execute the script inside schema.sql


  config:
#    optional - even if configserver is not connected, start the microservice
    import: "optional:configserver:http://localhost:8071/"

#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*" # telling enable and expose all management endpoints supported by actuator(one of them is refresh related endpoints)
  info:
    env:
      enabled: true

  endpoint:
    shutdown:
      access: unrestricted
    health:
      probes:
        enabled: true

  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true

  metrics:
    tags:
      application: ${spring.application.name}

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "accounts"
    description: "Accounts application of the Bank"
    version: "0.4"

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationOpenState: 10000

resilience4j.retry:
  configs:
    default:
      maxAttempts: 3
      waitDuration: 500
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
      ignoreExceptions:
        - java.lang.NullPointerException
#      retryExceptions:
#        - java.lang.TimeoutException   // If this configured, only the timeoutexception will be retired

logging:
  level:
    com:
      micro:
        accounts: DEBUG

resilience4j.ratelimiter:
  configs:
    default:
      timeoutDuration: 1000
      limitRefreshPeriod: 5000
      limitForPeriod: 1

#    highThroughput: # A custom config profile
#      timeoutDuration: 500
#      limitRefreshPeriod: 1000
#      limitForPeriod: 10
#
#  instances:
#    accountServiceLimiter1:
#      baseConfig: default
#
#    accountServiceLimiter2:
#      baseConfig: highThroughput