#spring:
#  application:
#    name: accounts

server:
  port: 8080



spring:
  datasource:
    url: jdbc:h2:mem:testdb  #  Uses an in-memory H2 database named testdb
    driverClassName: org.h2.Driver  #    Tells Spring which JDBC driver to use (H2 in this case).
    username: sa
    password: ''
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect    #  This tells Hibernate (the JPA provider) to generate SQL compatible with the H2 database.
    hibernate:
      ddl-auto: update   #  Automatically updates your database schema based on your JPA entity models.
    show-sql: true
  h2:
    console:
      enabled: true
